on:
  push:
  workflow_dispatch:
  pull_request:
jobs:
  oxlint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx --yes oxlint@1.6.0 --deny-warnings
  vitest:
    name: Test with coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm install
          npm ci
